#!/usr/bin/python3
"""Authenticated encryption for sensitive oVirt configuration files."""

import argparse
import base64
import getpass
import hashlib
import hmac
import json
import os
import pwd
import socket
import ssl
import stat
import struct
import sys
import tempfile
import termios
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives import hashes, padding, serialization
from cryptography.hazmat.primitives.asymmetric import padding as asym_padding
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.keywrap import aes_key_wrap_with_padding

try:
    from ovirt_engine import cryptoevents as _cryptoevents
except ImportError:
    _cryptoevents = None

try:
    # The engine's Hash_DRBG (SHA-256). Absent when this script is run on its own,
    # outside an installed engine, where os.urandom() serves as it always did.
    from ovirt_engine import csprng as _csprng
except ImportError:
    _csprng = None

MAGIC = b"OVENC001"
VAULT_MAGIC = b"OVVLT001"
# One data-encryption key (DEK) per installation, generated by the approved Hash_DRBG and kept
# only wrapped by the KEK in DEK_FILE. The configuration files are OVENC002 envelopes under it.
ENVELOPE_MAGIC = b"OVENC002"
DEK_MAGIC = b"OVDEK001"
DEK_FILE = Path("/etc/ovirt-engine/encryptor/dek.enc")
DEK_SALT_SIZE = 32
DEK_ID_SIZE = 8
# magic, version, PBKDF2 iterations, salt, nonce, wrapped DEK length
DEK_HEADER = struct.Struct(">8sBI32s12sH")
# magic, version, DEK id, nonce
ENVELOPE_HEADER = struct.Struct(">8sB8s12s")
VERSION = 1
PBKDF2_ITERATIONS = 600_000
SALT_SIZE = 16
NONCE_SIZE = 12
DATA_KEY_SIZE = 32
WRAPPED_KEY_SIZE = DATA_KEY_SIZE + 16
HEADER = struct.Struct(">8sBI16s12s12sH")
VAULT_HEADER = struct.Struct(">8sB12sH")
DEFAULT_CONFIG = Path("/etc/ovirt-engine/encryptor/config.json")
DEFAULT_CREDENTIAL = "ovirt-encryptor-passphrase"
PASSPHRASE_ENV = "OVIRT_ENCRYPTOR_PASSPHRASE"
# The key-encryption key held by Vault Transit is not generated by Vault: engine-setup derives it
# with PBKDF2 from initial data the operator types in, with a salt of its own for every
# installation, and imports it (see provision_pbkdf2_kek).
KEK_KDF = "PBKDF2-HMAC-SHA256"
KEK_PBKDF2_ITERATIONS = 600_000
KEK_SALT_SIZE = 32
KEK_SIZE = 32
KEK_MIN_PASSPHRASE = 16
KEK_MAX_PASSPHRASE = 256
# Without Vault: the passphrase the KEK is derived from is typed in at engine-setup and held in
# memory only, by ovirt-engine-kek-agent.service (kek_agent.py). Every OVENC001 file derives its
# KEK from it with PBKDF2-HMAC-SHA256 and a salt of its own, and that KEK wraps the file's DEK.
MEMORY_KEK_SOCKET = "/run/ovirt-engine-kek/agent.sock"
MEMORY_KEK_SOCKET_ROOT = "/run/"
MEMORY_MIN_PASSPHRASE = 6
MEMORY_MAX_PASSPHRASE = 256
ENGINE_SERVICE_USER = "ovirt"
_AGENT_MAX_HEADER = 1024
_AGENT_MAX_PAYLOAD = 4 * MEMORY_MAX_PASSPHRASE
ALLOWED_ROOTS = (Path("/etc/ovirt-engine"), Path("/etc/ovirt-engine-dwh"))
ALLOWED_CONFIG_BASENAMES = frozenset((
    "10-setup-database.conf",
    "10-setup-dwh-database.conf",
    "internal.properties",
))


def approved_random_bytes(count):
    """Key material: from the approved Hash_DRBG (SHA-256) only, never a fallback.

    random_bytes() falls back to os.urandom() where the engine's DRBG is missing; a key made
    there could not be shown to come from the approved generator, so this refuses instead.
    """
    if _csprng is None or not _csprng.is_approved():
        detail = _csprng.describe() if _csprng is not None else "ovirt_engine.csprng missing"
        raise EncryptorError(
            "The approved random bit generator (Hash_DRBG/SHA-256) is not available: %s"
            % detail)
    return _csprng.token_bytes(count)


def _record_event(event, source, error=None, **fields):
    """A cryptoevents entry, where the engine's python library is installed. Never raises."""
    if _cryptoevents is None:
        return
    try:
        if error is not None:
            fields["reason"] = _cryptoevents.reason_for(error)
        _cryptoevents.record(getattr(_cryptoevents, event), source, **fields)
    except Exception:
        pass


def random_bytes(count):
    """Keys, nonces and salts: from the engine's Hash_DRBG when it is installed."""
    if _csprng is None:
        return os.urandom(count)
    return _csprng.token_bytes(count)


class EncryptorError(RuntimeError):
    """A safe, user-facing encryption failure."""


class VaultTransitClient:
    """Small, dependency-free client for a local Vault Transit KMS."""

    def __init__(self, settings, token=None, key_name=None):
        """
        @param token an administrative token typed in by the operator and kept in memory only,
                     used instead of the service token file - for importing the KEK
        @param key_name the Transit key to address instead of the configured one
        """
        if not isinstance(settings, dict):
            raise EncryptorError("vault_transit configuration must be an object")
        self.address = settings.get("address", "https://127.0.0.1:8200").rstrip("/")
        parsed = urllib.parse.urlparse(self.address)
        if parsed.scheme not in ("http", "https"):
            raise EncryptorError("Vault address must use HTTP or HTTPS")
        allow_plaintext = settings.get("allow_plaintext_loopback", False)
        if not isinstance(allow_plaintext, bool):
            raise EncryptorError(
                "vault_transit.allow_plaintext_loopback must be true or false"
            )
        if parsed.scheme == "http" and not (
                allow_plaintext
                and parsed.hostname in ("127.0.0.1", "::1", "localhost")):
            raise EncryptorError(
                "Plain HTTP Vault is disabled; use HTTPS with a matching SAN, "
                "or set vault_transit.allow_plaintext_loopback=true only for "
                "an explicitly accepted loopback-only deployment"
            )
        self.mount = settings.get("mount", "transit").strip("/")
        self.key_name = key_name or settings.get("key_name", "ovirt-engine-config")
        if not self.mount or "/" in self.mount or not self.key_name or "/" in self.key_name:
            raise EncryptorError("Invalid Vault Transit mount or key name")
        self.token_file = Path(settings.get(
            "token_file", "/etc/ovirt-engine/encryptor/vault-token"
        ))
        if token is not None:
            self.token = _vault_token_text(token)
        else:
            if not self.token_file.exists():
                raise EncryptorError(
                    "Vault token file is missing: %s; provision a least-privilege "
                    "Transit token before running engine-setup" % self.token_file
                )
            try:
                self.token = _read_secret_file(self.token_file).decode("utf-8")
            except UnicodeDecodeError as error:
                raise EncryptorError("Vault token file is not valid UTF-8") from error
        self.namespace = settings.get("namespace")
        ca_cert = settings.get("ca_cert")
        if ca_cert and not Path(ca_cert).is_file():
            raise EncryptorError("Vault CA certificate is missing: %s" % ca_cert)
        context = ssl.create_default_context(cafile=ca_cert)
        self.opener = urllib.request.build_opener(urllib.request.HTTPSHandler(context=context))
        self.timeout = int(settings.get("timeout", 5))

    def _request(self, operation, payload):
        return self._call("POST", "%s/%s" % (
            operation, urllib.parse.quote(self.key_name, safe="")
        ), payload, empty_ok=(operation == "keys"))

    def _call(self, method, path, payload=None, empty_ok=False, missing_ok=False):
        """One Transit API call; {} for an empty body where that is a success, None for a 404
        where the caller asked whether something exists."""
        url = "%s/v1/%s/%s" % (
            self.address,
            urllib.parse.quote(self.mount, safe=""),
            path,
        )
        headers = {"Content-Type": "application/json", "X-Vault-Token": self.token}
        if self.namespace:
            headers["X-Vault-Namespace"] = self.namespace
        data = None if payload is None else json.dumps(payload).encode("utf-8")
        request = urllib.request.Request(url, data=data, headers=headers, method=method)
        try:
            with self.opener.open(request, timeout=self.timeout) as response:
                body = response.read()
                if empty_ok and not body:
                    return {}
                result = json.loads(body.decode("utf-8"))
        except urllib.error.HTTPError as error:
            if missing_ok and error.code == 404:
                return None
            raise EncryptorError(
                "Vault Transit request failed (HTTP %s%s)" % (error.code, _vault_errors(error))
            ) from error
        except urllib.error.URLError as error:
            if isinstance(error.reason, ssl.SSLCertVerificationError):
                raise EncryptorError(
                    "Vault TLS certificate verification failed: the configured "
                    "address must match a certificate subjectAltName and the "
                    "configured CA must trust the certificate"
                ) from error
            raise EncryptorError("Vault Transit connection failed") from error
        except (OSError, ValueError) as error:
            raise EncryptorError("Vault Transit request failed") from error
        if not isinstance(result, dict) or not isinstance(result.get("data"), dict):
            raise EncryptorError("Vault Transit returned an invalid response")
        return result["data"]

    def ensure_key(self):
        """Ask Vault to generate and retain a non-exportable AES-256 KEK."""
        self._request("keys", {
            "type": "aes256-gcm96",
            "exportable": False,
            "allow_plaintext_backup": False,
        })

    def key_exists(self):
        """Whether the Transit key exists. Needs read on transit/keys/<name>."""
        return self._call(
            "GET", "keys/%s" % urllib.parse.quote(self.key_name, safe=""), missing_ok=True
        ) is not None

    def wrapping_key(self):
        """Vault's RSA public key for importing key material into Transit."""
        result = self._call("GET", "wrapping_key")
        try:
            return serialization.load_pem_public_key(result["public_key"].encode("ascii"))
        except (KeyError, AttributeError, TypeError, ValueError) as error:
            raise EncryptorError("Vault Transit returned an invalid wrapping key") from error

    def import_key(self, kek):
        """Import a 256-bit KEK as a new, non-exportable aes256-gcm96 Transit key.

        Vault never rotates it itself (allow_rotation=false): a version it generated would be
        random, not derived, and the derivation is the point. Import only creates a key - it
        cannot replace one that exists.
        """
        if len(kek) != KEK_SIZE:
            raise EncryptorError("The KEK must be %d bytes" % KEK_SIZE)
        ephemeral = bytearray(random_bytes(KEK_SIZE))
        try:
            ciphertext = build_import_ciphertext(kek, self.wrapping_key(), ephemeral)
        finally:
            wipe(ephemeral)
        self._call("POST", "keys/%s/import" % urllib.parse.quote(self.key_name, safe=""), {
            "ciphertext": ciphertext,
            "hash_function": "SHA256",
            "type": "aes256-gcm96",
            "exportable": False,
            "allow_plaintext_backup": False,
            "allow_rotation": False,
        }, empty_ok=True)

    def wrap(self, plaintext):
        result = self._request("encrypt", {
            "plaintext": base64.b64encode(plaintext).decode("ascii"),
        })
        ciphertext = result.get("ciphertext")
        if not isinstance(ciphertext, str) or not ciphertext.startswith("vault:v"):
            raise EncryptorError("Vault Transit did not return wrapped key material")
        return ciphertext.encode("ascii")

    def unwrap(self, ciphertext):
        result = self._request("decrypt", {"ciphertext": ciphertext.decode("ascii")})
        try:
            return base64.b64decode(result["plaintext"], validate=True)
        except (KeyError, TypeError, ValueError) as error:
            raise EncryptorError("Vault Transit did not return valid key material") from error


def _vault_token_text(token):
    if isinstance(token, str):
        value = token.strip()
    else:
        try:
            value = bytes(token).decode("ascii").strip()
        except UnicodeDecodeError as error:
            raise EncryptorError("The Vault token is empty or malformed") from error
    if not value or len(value) > 4096 or any(ord(c) <= 0x20 or ord(c) > 0x7e for c in value):
        raise EncryptorError("The Vault token is empty or malformed")
    return value


def _vault_errors(error):
    """Vault's own error text, which says what was wrong ("permission denied", "key exists")."""
    try:
        errors = json.loads(error.read().decode("utf-8")).get("errors")
    except Exception:
        return ""
    if not isinstance(errors, list) or not errors:
        return ""
    return ": " + "; ".join(str(item) for item in errors)[:300]


def wipe(buffer):
    """Overwrites a bytearray holding a secret. Python cannot do this for str or bytes."""
    if isinstance(buffer, bytearray):
        for index in range(len(buffer)):
            buffer[index] = 0


def check_kek_passphrase(passphrase):
    """The initial data a KEK is derived from: long and varied enough to be worth deriving from."""
    if len(passphrase) < KEK_MIN_PASSPHRASE:
        raise EncryptorError(
            "The KEK passphrase must be at least %d characters" % KEK_MIN_PASSPHRASE)
    if len(passphrase) > KEK_MAX_PASSPHRASE:
        raise EncryptorError(
            "The KEK passphrase must be at most %d characters" % KEK_MAX_PASSPHRASE)
    text = bytes(passphrase).decode("utf-8", "replace")
    classes = sum((
        any(c.islower() for c in text),
        any(c.isupper() for c in text),
        any(c.isdigit() for c in text),
        any(not c.isalnum() for c in text),
    ))
    if classes < 3:
        raise EncryptorError(
            "The KEK passphrase must mix at least three of: lower case, upper case, digits, "
            "other characters")


def derive_kek(passphrase, salt, iterations=KEK_PBKDF2_ITERATIONS):
    """KEK = PBKDF2-HMAC-SHA256(passphrase, salt, iterations), 256 bits, as a bytearray."""
    if iterations < KEK_PBKDF2_ITERATIONS:
        raise EncryptorError("PBKDF2 iteration count is below the security minimum")
    if len(salt) < KEK_SALT_SIZE:
        raise EncryptorError("The KEK salt must be at least %d bytes" % KEK_SALT_SIZE)
    return bytearray(PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=KEK_SIZE,
        salt=bytes(salt),
        iterations=iterations,
    ).derive(bytes(passphrase)))


def build_import_ciphertext(kek, wrapping_public_key, ephemeral):
    """The ciphertext Vault Transit's import takes: the ephemeral AES-256 key encrypted with
    RSA-OAEP (SHA-256) under Vault's wrapping key, followed by the KEK wrapped with that ephemeral
    key by AES key wrap with padding (RFC 5649), base64-encoded."""
    wrapped_ephemeral = wrapping_public_key.encrypt(
        bytes(ephemeral),
        asym_padding.OAEP(
            mgf=asym_padding.MGF1(algorithm=hashes.SHA256()),
            algorithm=hashes.SHA256(),
            label=None,
        ),
    )
    wrapped_kek = aes_key_wrap_with_padding(bytes(ephemeral), bytes(kek))
    return base64.b64encode(wrapped_ephemeral + wrapped_kek).decode("ascii")


def kek_matches_vault(kek, client):
    """Whether the key Vault now holds is the derived KEK.

    Vault encrypts a probe with its key; the probe is then opened here with the derived KEK.
    Transit's aes256-gcm96 ciphertext is vault:v<n>:base64(nonce(12) || ciphertext || tag(16)).
    @return True when it opens, False when it does not, None when the answer was not readable
    """
    probe = random_bytes(16)
    try:
        wrapped = client.wrap(probe).decode("ascii")
        raw = base64.b64decode(wrapped.split(":", 2)[2], validate=True)
    except (EncryptorError, IndexError, ValueError):
        return None
    if len(raw) < NONCE_SIZE + 16:
        return None
    try:
        return AESGCM(bytes(kek)).decrypt(raw[:NONCE_SIZE], raw[NONCE_SIZE:], None) == probe
    except InvalidTag:
        return False


def new_kek_salt():
    """A salt of this installation's own, so no two products derive the same KEK."""
    return random_bytes(KEK_SALT_SIZE)


def kek_derivation_record(salt, key_name, iterations=KEK_PBKDF2_ITERATIONS):
    """What config.json keeps about the KEK. Nothing in it is secret; with the passphrase - which
    is kept nowhere on the host - it re-derives the KEK should Vault's data be lost."""
    return {
        "kdf": KEK_KDF,
        "iterations": iterations,
        "salt": base64.b64encode(bytes(salt)).decode("ascii"),
        "key_length_bits": KEK_SIZE * 8,
        "key_name": key_name,
        "salt_rng": "Hash_DRBG(SHA-256)" if _csprng is not None else "os.urandom",
    }


def provision_pbkdf2_kek(settings, admin_token, passphrase, salt=None, adopt_existing=False):
    """Derive the KEK from the operator's passphrase and import it into Vault Transit.

    The passphrase, the admin token and the derived KEK exist only in this process's memory; the
    KEK is overwritten once Vault has it. Refuses when the key already exists - Vault's import
    cannot replace one, and a second KEK would orphan every file the first one protects - unless
    adopt_existing is set and the key there is the one this passphrase and salt derive: that is
    an import whose record was not finished, and it is finished now.

    Callers record the salt (status "pending") before calling this, so that an import whose
    record is lost to a failure afterwards can still be re-derived.

    @return the derivation record for config.json, status "active"
    """
    check_kek_passphrase(passphrase)
    admin = VaultTransitClient(settings, token=admin_token)
    salt = bytes(salt) if salt is not None else new_kek_salt()
    kek = derive_kek(passphrase, salt)
    try:
        exists = admin.key_exists()
        if exists and not adopt_existing:
            raise EncryptorError(
                "Vault Transit key %s already exists; a KEK is imported only once. Use a new "
                "key name to replace it (see --rewrap-to-key)" % admin.key_name)
        if not exists:
            admin.import_key(kek)
        # Checked through the engine's own service token: that also proves the token can use the
        # new key, which is what every start of the engine will need.
        try:
            verified = kek_matches_vault(kek, VaultTransitClient(settings, key_name=admin.key_name))
        except EncryptorError:
            verified = None
    finally:
        wipe(kek)
    if exists and verified is not True:
        raise EncryptorError(
            "Vault Transit key %s exists and is not the KEK this passphrase and salt derive"
            % admin.key_name)
    record = kek_derivation_record(salt, admin.key_name)
    # False would mean Vault's ciphertext did not open with the derived key; the import itself
    # carried exactly these bytes, so it is reported rather than taken as a failed import.
    record["verified"] = verified
    record["status"] = "active"
    return record


def vault_client_from_config(config):
    settings = config.get("vault_transit")
    if settings is None:
        return None
    if not isinstance(settings, dict):
        raise EncryptorError("vault_transit configuration must be a JSON object")
    enabled = settings.get("enabled", False)
    if not isinstance(enabled, bool):
        raise EncryptorError("vault_transit.enabled must be true or false")
    return VaultTransitClient(settings) if enabled else None


def memory_kek_settings(config):
    """The kek_agent settings when the KEK passphrase is held in memory, else None."""
    settings = config.get("kek_agent")
    if settings is None:
        return None
    if not isinstance(settings, dict):
        raise EncryptorError("kek_agent configuration must be a JSON object")
    enabled = settings.get("enabled", False)
    if not isinstance(enabled, bool):
        raise EncryptorError("kek_agent.enabled must be true or false")
    if not enabled:
        return None
    socket_path = settings.get("socket", MEMORY_KEK_SOCKET)
    if not isinstance(socket_path, str) or not socket_path.startswith(MEMORY_KEK_SOCKET_ROOT):
        raise EncryptorError("kek_agent.socket must be a path below /run")
    return {"socket": socket_path}


def passphrase_length(passphrase):
    """Characters, not bytes, of a UTF-8 passphrase - counted without making a str of it."""
    return sum(1 for byte in passphrase if byte & 0xC0 != 0x80)


def check_memory_passphrase(passphrase):
    """The rule for the passphrase typed in at engine-setup: 6 to 256 characters."""
    length = passphrase_length(passphrase)
    if not MEMORY_MIN_PASSPHRASE <= length <= MEMORY_MAX_PASSPHRASE:
        raise EncryptorError(
            "KEK passphrase must be %d to %d characters"
            % (MEMORY_MIN_PASSPHRASE, MEMORY_MAX_PASSPHRASE))
    if any(byte < 0x20 or byte == 0x7F for byte in passphrase):
        raise EncryptorError("KEK passphrase must not contain control characters")


def agent_send(conn, header, payload=None):
    """One message to or from the KEK agent: a JSON line, then `length` raw bytes.

    The secret is never in the JSON: it travels as raw bytes straight from and into a
    bytearray, so it is never copied into an immutable str or bytes that cannot be wiped.
    """
    header = dict(header, length=0 if payload is None else len(payload))
    conn.sendall(json.dumps(header, sort_keys=True).encode("ascii") + b"\n")
    if payload:
        conn.sendall(payload)


def agent_receive(conn):
    """@return (header, payload) where payload is a bytearray, or None when there is none"""
    line = bytearray()
    while not line.endswith(b"\n"):
        chunk = conn.recv(1)
        if not chunk:
            raise EncryptorError("KEK agent message is truncated")
        line += chunk
        if len(line) > _AGENT_MAX_HEADER:
            raise EncryptorError("KEK agent message is too long")
    try:
        header = json.loads(bytes(line).decode("ascii"))
    except ValueError as error:
        raise EncryptorError("KEK agent message is malformed") from error
    if not isinstance(header, dict):
        raise EncryptorError("KEK agent message is malformed")
    length = header.get("length", 0)
    if not isinstance(length, int) or not 0 <= length <= _AGENT_MAX_PAYLOAD:
        raise EncryptorError("KEK agent message is malformed")
    if not length:
        return header, None
    payload = bytearray(length)
    view = memoryview(payload)
    received = 0
    while received < length:
        count = conn.recv_into(view[received:])
        if not count:
            wipe(payload)
            raise EncryptorError("KEK agent message is truncated")
        received += count
    return header, payload


def _peer_uid(conn):
    data = conn.getsockopt(socket.SOL_SOCKET, socket.SO_PEERCRED, struct.calcsize("3i"))
    return struct.unpack("3i", data)[1]


def _trusted_agent_uids():
    uids = {0, os.geteuid()}
    try:
        uids.add(pwd.getpwnam(ENGINE_SERVICE_USER).pw_uid)
    except KeyError:
        pass
    return uids


def kek_agent_request(socket_path, op, payload=None):
    """Asks the KEK agent for one thing. @return (header, payload)"""
    try:
        with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as conn:
            conn.settimeout(10)
            conn.connect(socket_path)
            # The passphrase goes only to an agent run by root or the engine's own account.
            if _peer_uid(conn) not in _trusted_agent_uids():
                raise EncryptorError("KEK agent socket is owned by an untrusted account")
            agent_send(conn, {"op": op}, payload)
            header, answer = agent_receive(conn)
    except OSError as error:
        raise EncryptorError(
            "KEK agent is not reachable at %s; start ovirt-engine-kek-agent.service"
            % socket_path) from error
    if header.get("ok") is not True:
        if answer is not None:
            wipe(answer)
        if header.get("error") == "not-loaded":
            raise EncryptorError(
                "KEK passphrase is not loaded in memory; run "
                "/usr/share/ovirt-engine/encryptor/kek_agent.py --unlock")
        raise EncryptorError("KEK agent refused the request: %s" % header.get("error"))
    return header, answer


def fetch_memory_passphrase(socket_path):
    """The passphrase the agent holds, as a bytearray the caller can wipe."""
    _header, passphrase = kek_agent_request(socket_path, "get")
    if passphrase is None:
        raise EncryptorError(
            "KEK passphrase is not loaded in memory; run "
            "/usr/share/ovirt-engine/encryptor/kek_agent.py --unlock")
    return passphrase


def load_memory_passphrase(socket_path, passphrase):
    check_memory_passphrase(passphrase)
    kek_agent_request(socket_path, "load", passphrase)


def memory_passphrase_loaded(socket_path):
    header, _answer = kek_agent_request(socket_path, "status")
    return header.get("loaded") is True


def read_secret(prompt, stream_in=None, stream_out=None):
    """Reads one line from the terminal without echo, into a bytearray the caller can wipe.

    Not getpass: that returns an immutable str, which Python can never overwrite.
    """
    tty = stream_in or open("/dev/tty", "rb", buffering=0)
    out = stream_out or sys.stderr
    fd = tty.fileno() if stream_in is None else None
    old = None
    if fd is not None:
        old = termios.tcgetattr(fd)
        new = termios.tcgetattr(fd)
        new[3] &= ~termios.ECHO
        termios.tcsetattr(fd, termios.TCSAFLUSH, new)
    secret = bytearray()
    try:
        out.write(prompt)
        out.flush()
        while True:
            char = tty.read(1)
            if not char or char in (b"\n", b"\r"):
                break
            secret += char
            if len(secret) > 4096:
                raise EncryptorError("Input is too long")
    finally:
        if old is not None:
            termios.tcsetattr(fd, termios.TCSAFLUSH, old)
        out.write("\n")
        if stream_in is None:
            tty.close()
    return secret


def _load_crypto_config(path):
    path = Path(path)
    try:
        exists = path.exists()
    except PermissionError as error:
        raise EncryptorError(
            "Encryptor configuration is not accessible: %s; the service "
            "account needs directory traverse and file read permission" % path
        ) from error
    if not exists:
        return {}
    _validate_regular_file(path, reject_writable=True)
    try:
        with path.open(encoding="utf-8") as stream:
            value = json.load(stream)
    except (OSError, ValueError) as error:
        raise EncryptorError("Unable to read encryptor configuration") from error
    if not isinstance(value, dict):
        raise EncryptorError("Encryptor configuration must be a JSON object")
    return value


def _validate_regular_file(path, reject_writable=False):
    path = Path(path)
    try:
        info = path.lstat()
    except OSError as error:
        raise EncryptorError("Unable to inspect path: %s" % path) from error
    if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode):
        raise EncryptorError("Refusing non-regular or symbolic-link file: %s" % path)
    if reject_writable and info.st_mode & (stat.S_IWGRP | stat.S_IWOTH):
        raise EncryptorError("Refusing group/other-writable file: %s" % path)
    return info


def _within_allowed_root(path, allowed_roots=ALLOWED_ROOTS):
    resolved = Path(path).resolve(strict=False)
    return any(resolved == root or root in resolved.parents for root in allowed_roots)


def validate_ovirt_path(path, must_exist=True, allowed_roots=ALLOWED_ROOTS):
    path = Path(path)
    if not _within_allowed_root(path, allowed_roots):
        raise EncryptorError("Path is outside approved oVirt directories: %s" % path)
    current = path if must_exist else path.parent
    while True:
        if current.exists() and stat.S_ISLNK(current.lstat().st_mode):
            raise EncryptorError("Symbolic links are not allowed: %s" % current)
        if current.parent == current:
            break
        current = current.parent
    if must_exist:
        return _validate_regular_file(path, reject_writable=True)
    return None


def is_encrypted(data_or_path):
    if isinstance(data_or_path, (str, Path)):
        with Path(data_or_path).open("rb") as stream:
            prefix = stream.read(len(MAGIC))
    else:
        prefix = bytes(data_or_path[:len(MAGIC)])
    return prefix in (MAGIC, VAULT_MAGIC, ENVELOPE_MAGIC)


def _read_secret_file(path, transit_client=None):
    info = _validate_regular_file(path, reject_writable=True)
    if info.st_mode & (stat.S_IRWXG | stat.S_IRWXO):
        raise EncryptorError("Passphrase file permissions must be 0600 or stricter")
    try:
        with Path(path).open("rb") as stream:
            secret = stream.read().rstrip(b"\r\n")
    except PermissionError as error:
        raise EncryptorError(
            "Secret file is not readable by the service account: %s" % path
        ) from error
    if transit_client is not None and secret.startswith(VAULT_MAGIC):
        secret = decrypt_vault_bytes(secret, transit_client)
    if not secret:
        raise EncryptorError("Passphrase file is empty")
    return secret


def obtain_passphrase(config, secret_file=None, allow_prompt=False, transit_client=None):
    """Load a passphrase without hardware identifiers or command-line values."""
    memory = memory_kek_settings(config)
    if memory is not None:
        # Held in memory only: nothing on disk or in the environment stands in for it.
        return fetch_memory_passphrase(memory["socket"])
    credential_dir = os.environ.get("CREDENTIALS_DIRECTORY")
    credential_name = config.get("systemd_credential", DEFAULT_CREDENTIAL)
    if credential_dir:
        credential_path = Path(credential_dir) / credential_name
        if credential_path.exists():
            return _read_secret_file(credential_path, transit_client)
    environment_secret = os.environ.get(PASSPHRASE_ENV)
    if environment_secret:
        return environment_secret.encode("utf-8")
    configured_file = secret_file or config.get("secret_file")
    if configured_file:
        return _read_secret_file(configured_file, transit_client)
    if allow_prompt and sys.stdin.isatty():
        secret = getpass.getpass("Encryption passphrase: ").encode("utf-8")
        if secret:
            return secret
    raise EncryptorError(
        "No key credential available (systemd credential, environment, or 0600 secret file)"
    )


def _derive_kek(passphrase, salt, iterations=PBKDF2_ITERATIONS):
    if iterations < PBKDF2_ITERATIONS:
        raise EncryptorError("PBKDF2 iteration count is below the security minimum")
    return PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=iterations,
    ).derive(passphrase)


def encrypt_bytes(plaintext, passphrase):
    salt = random_bytes(SALT_SIZE)
    key_nonce = random_bytes(NONCE_SIZE)
    data_nonce = random_bytes(NONCE_SIZE)
    data_key = random_bytes(DATA_KEY_SIZE)
    fixed_header = HEADER.pack(
        MAGIC,
        VERSION,
        PBKDF2_ITERATIONS,
        salt,
        key_nonce,
        data_nonce,
        WRAPPED_KEY_SIZE,
    )
    kek = _derive_kek(passphrase, salt)
    wrapped_key = AESGCM(kek).encrypt(key_nonce, data_key, fixed_header)
    ciphertext = AESGCM(data_key).encrypt(
        data_nonce,
        plaintext,
        fixed_header + wrapped_key,
    )
    return fixed_header + wrapped_key + ciphertext


def encrypt_vault_bytes(plaintext, transit_client):
    """Envelope-encrypt bytes with a random DEK wrapped by Vault Transit."""
    data_key = random_bytes(DATA_KEY_SIZE)
    data_nonce = random_bytes(NONCE_SIZE)
    wrapped_key = transit_client.wrap(data_key)
    if len(wrapped_key) > 65535:
        raise EncryptorError("Vault wrapped data key is too large")
    fixed_header = VAULT_HEADER.pack(
        VAULT_MAGIC, VERSION, data_nonce, len(wrapped_key)
    )
    ciphertext = AESGCM(data_key).encrypt(
        data_nonce, plaintext, fixed_header + wrapped_key
    )
    return fixed_header + wrapped_key + ciphertext


def decrypt_vault_bytes(data, transit_client):
    if len(data) < VAULT_HEADER.size + 16:
        raise EncryptorError("Vault-encrypted file is truncated")
    magic, version, data_nonce, wrapped_size = VAULT_HEADER.unpack_from(data)
    if magic != VAULT_MAGIC or version != VERSION or not wrapped_size:
        raise EncryptorError("Invalid Vault envelope header")
    end = VAULT_HEADER.size + wrapped_size
    if len(data) < end + 16:
        raise EncryptorError("Vault-encrypted file is truncated")
    fixed_header, wrapped_key, ciphertext = data[:VAULT_HEADER.size], data[VAULT_HEADER.size:end], data[end:]
    data_key = transit_client.unwrap(wrapped_key)
    if len(data_key) != DATA_KEY_SIZE:
        raise EncryptorError("Vault returned an invalid data key length")
    try:
        return AESGCM(data_key).decrypt(
            data_nonce, ciphertext, fixed_header + wrapped_key
        )
    except InvalidTag as error:
        raise EncryptorError("Authentication failed: file is damaged or modified") from error


def _parse_gcm(data):
    if len(data) < HEADER.size + WRAPPED_KEY_SIZE + 16:
        raise EncryptorError("Encrypted file is truncated")
    magic, version, iterations, salt, key_nonce, data_nonce, wrapped_size = HEADER.unpack_from(data)
    if magic != MAGIC:
        raise EncryptorError("Encrypted file magic header is missing")
    if version != VERSION:
        raise EncryptorError("Unsupported encrypted file version: %s" % version)
    if iterations != PBKDF2_ITERATIONS:
        raise EncryptorError("Invalid PBKDF2 iteration count for this format version")
    if wrapped_size != WRAPPED_KEY_SIZE:
        raise EncryptorError("Invalid wrapped data-key length")
    end = HEADER.size + wrapped_size
    return iterations, salt, key_nonce, data_nonce, data[HEADER.size:end], data[end:], data[:HEADER.size]


def decrypt_gcm_bytes(data, passphrase):
    iterations, salt, key_nonce, data_nonce, wrapped_key, ciphertext, fixed_header = _parse_gcm(data)
    try:
        kek = _derive_kek(passphrase, salt, iterations)
        data_key = AESGCM(kek).decrypt(key_nonce, wrapped_key, fixed_header)
        return AESGCM(data_key).decrypt(
            data_nonce,
            ciphertext,
            fixed_header + wrapped_key,
        )
    except InvalidTag as error:
        raise EncryptorError("Authentication failed: file is damaged, modified, or the key is wrong") from error


def _decode_legacy_value(value, name):
    if not value:
        raise EncryptorError("Legacy CBC %s is not configured" % name)
    try:
        if value.startswith("hex:"):
            return bytes.fromhex(value[4:])
        if len(value) == 64:
            return bytes.fromhex(value)
        return base64.b64decode(value, validate=True)
    except (ValueError, TypeError) as error:
        raise EncryptorError("Invalid legacy CBC %s encoding" % name) from error


def decrypt_legacy_cbc(data, config):
    """Migration-only CBC reader; it never writes legacy ciphertext."""
    legacy = config.get("legacy_cbc")
    if not isinstance(legacy, dict) or not legacy.get("enabled", False):
        raise EncryptorError("Legacy CBC format is not enabled in the configuration")
    key = _decode_legacy_value(legacy.get("key"), "key")
    if len(key) != 32:
        raise EncryptorError("Legacy CBC key must be exactly 256 bits")
    if legacy.get("base64", False):
        try:
            data = base64.b64decode(data, validate=True)
        except (ValueError, TypeError) as error:
            raise EncryptorError("Legacy CBC ciphertext is not valid Base64") from error
    if legacy.get("iv_prefix", True):
        if len(data) < 32:
            raise EncryptorError("Legacy CBC file is truncated")
        iv, ciphertext = data[:16], data[16:]
    else:
        iv = _decode_legacy_value(legacy.get("iv"), "IV")
        ciphertext = data
    if len(iv) != 16 or not ciphertext or len(ciphertext) % 16:
        raise EncryptorError("Legacy CBC IV or ciphertext length is invalid")
    decryptor = Cipher(algorithms.AES(key), modes.CBC(iv)).decryptor()
    padded = decryptor.update(ciphertext) + decryptor.finalize()
    try:
        unpadder = padding.PKCS7(128).unpadder()
        return unpadder.update(padded) + unpadder.finalize()
    except ValueError as error:
        raise EncryptorError("Legacy CBC decryption failed") from error


def dek_file_path(config, allowed_roots=ALLOWED_ROOTS):
    path = Path((config or {}).get("dek_file", str(DEK_FILE)))
    if not _within_allowed_root(path, allowed_roots):
        raise EncryptorError("dek_file is outside approved oVirt directories: %s" % path)
    return path


def dek_id(dek):
    """Names a DEK in the envelopes it encrypts without revealing it."""
    return hmac.new(bytes(dek), b"ovirt-engine dek id", hashlib.sha256).digest()[:DEK_ID_SIZE]


def wrap_dek(dek, passphrase, iterations=PBKDF2_ITERATIONS):
    """The DEK file: the DEK under AES-256-GCM with a KEK PBKDF2 derives from the passphrase."""
    salt = approved_random_bytes(DEK_SALT_SIZE)
    nonce = approved_random_bytes(NONCE_SIZE)
    header = DEK_HEADER.pack(DEK_MAGIC, VERSION, iterations, salt, nonce, WRAPPED_KEY_SIZE)
    kek = _derive_kek(passphrase, salt, iterations)
    return header + AESGCM(kek).encrypt(nonce, bytes(dek), header)


def unwrap_dek(data, passphrase):
    """@return the DEK, as a bytearray the caller wipes"""
    if len(data) != DEK_HEADER.size + WRAPPED_KEY_SIZE:
        raise EncryptorError("DEK file is truncated or malformed")
    magic, version, iterations, salt, nonce, wrapped_size = DEK_HEADER.unpack_from(data)
    if magic != DEK_MAGIC or version != VERSION or wrapped_size != WRAPPED_KEY_SIZE:
        raise EncryptorError("DEK file magic header is missing or unsupported")
    header = data[:DEK_HEADER.size]
    kek = _derive_kek(passphrase, salt, iterations)
    try:
        return bytearray(AESGCM(kek).decrypt(nonce, data[DEK_HEADER.size:], header))
    except InvalidTag as error:
        raise EncryptorError(
            "Authentication failed: the DEK file does not open with this KEK passphrase"
        ) from error


def read_dek(config, passphrase, allowed_roots=ALLOWED_ROOTS):
    path = dek_file_path(config, allowed_roots)
    if not path.exists():
        raise EncryptorError("DEK file is missing: %s" % path)
    _validate_regular_file(path, reject_writable=True)
    return unwrap_dek(path.read_bytes(), passphrase)


def ensure_dek(config, passphrase, source="encryptor", allowed_roots=ALLOWED_ROOTS):
    """The installation's DEK: the existing one, or one generated and stored now.

    Generated by the approved Hash_DRBG only, wrapped by the KEK, verified, and written
    root:<directory group> 0640 so the engine's account can read it and nobody can change it.
    Creating it, and failing to obtain a usable DEK, are recorded as audit events.

    @return (dek, created) - dek is a bytearray the caller wipes
    """
    path = dek_file_path(config, allowed_roots)
    fields = {"file": path.name, "scheme": DEK_MAGIC.decode("ascii")}
    try:
        if path.exists():
            return read_dek(config, passphrase, allowed_roots), False
        dek = bytearray(approved_random_bytes(DATA_KEY_SIZE))
        data = wrap_dek(dek, passphrase)
        if unwrap_dek(data, passphrase) != dek:
            raise EncryptorError("DEK self-verification failed")
        owner = None
        if os.geteuid() == 0:
            owner = (0, path.parent.stat().st_gid)
        _atomic_write(path, data, owner=owner, mode=0o640)
    except Exception as error:
        _record_event("KEY_CREATION_FAILED", source, error, **fields)
        raise
    _record_event("KEY_CREATED", source, **fields)
    return dek, True


def encrypted_targets(config, magics=(MAGIC, VAULT_MAGIC, ENVELOPE_MAGIC)):
    """The protected configuration files that are encrypted, as encrypt_conf_files.py finds
    them: the allowed basenames below every watch_path."""
    names = set(config.get("allowed_files", sorted(ALLOWED_CONFIG_BASENAMES)))
    if not names <= ALLOWED_CONFIG_BASENAMES:
        raise EncryptorError("allowed_files contains an unapproved filename")
    targets = []
    for root in config.get("watch_path", [str(path) for path in ALLOWED_ROOTS]):
        root = Path(root)
        if not _within_allowed_root(root) or root.is_symlink() or not root.is_dir():
            continue
        for directory, directories, files in os.walk(str(root), followlinks=False):
            directories[:] = [d for d in directories if not (Path(directory) / d).is_symlink()]
            for name in sorted(files):
                path = Path(directory) / name
                if name in names and not path.is_symlink() and path.is_file():
                    with path.open("rb") as stream:
                        if stream.read(len(MAGIC)) in magics:
                            targets.append(path)
    return targets


def encrypt_envelope(plaintext, dek):
    nonce = approved_random_bytes(NONCE_SIZE)
    header = ENVELOPE_HEADER.pack(ENVELOPE_MAGIC, VERSION, dek_id(dek), nonce)
    return header + AESGCM(bytes(dek)).encrypt(nonce, plaintext, header)


def decrypt_envelope(data, dek):
    if len(data) < ENVELOPE_HEADER.size + 16:
        raise EncryptorError("Encrypted file is truncated")
    magic, version, key_id, nonce = ENVELOPE_HEADER.unpack_from(data)
    if magic != ENVELOPE_MAGIC:
        raise EncryptorError("Encrypted file magic header is missing")
    if version != VERSION:
        raise EncryptorError("Unsupported encrypted file version: %s" % version)
    if not hmac.compare_digest(key_id, dek_id(dek)):
        raise EncryptorError("The file is encrypted under another DEK than dek_file holds")
    header = data[:ENVELOPE_HEADER.size]
    try:
        return AESGCM(bytes(dek)).decrypt(nonce, data[ENVELOPE_HEADER.size:], header)
    except InvalidTag as error:
        raise EncryptorError("Authentication failed: file is damaged or modified") from error


def decrypt_bytes(data, passphrase=None, config=None, deny_legacy_cbc=False,
                  transit_client=None, allowed_roots=ALLOWED_ROOTS):
    if data.startswith(ENVELOPE_MAGIC):
        if passphrase is None:
            raise EncryptorError("A passphrase is required for the DEK file")
        dek = read_dek(config or {}, passphrase, allowed_roots)
        try:
            return decrypt_envelope(data, dek)
        finally:
            wipe(dek)
    if data.startswith(VAULT_MAGIC):
        if transit_client is None:
            raise EncryptorError("Vault Transit is required for this encrypted file")
        return decrypt_vault_bytes(data, transit_client)
    if data.startswith(MAGIC):
        if passphrase is None:
            raise EncryptorError("A passphrase is required for the legacy envelope format")
        return decrypt_gcm_bytes(data, passphrase)
    if deny_legacy_cbc:
        raise EncryptorError("Legacy AES-CBC ciphertext is denied")
    return decrypt_legacy_cbc(data, config or {})


def _atomic_write(path, data, owner=None, mode=0o600):
    path = Path(path)
    descriptor, temporary = tempfile.mkstemp(prefix=".%s." % path.name, dir=str(path.parent))
    temporary_path = Path(temporary)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary_path, mode)
        if owner is not None:
            os.chown(temporary_path, owner[0], owner[1])
        os.replace(temporary_path, path)
        directory_fd = os.open(str(path.parent), os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    finally:
        if temporary_path.exists():
            temporary_path.unlink()


def atomic_update_config(path, config):
    """Persist non-secret metadata with the same atomicity as ciphertext."""
    path = Path(path)
    info = validate_ovirt_path(path)
    content = (json.dumps(config, indent=4, sort_keys=True) + "\n").encode("utf-8")
    _atomic_write(
        path,
        content,
        owner=(info.st_uid, info.st_gid),
        mode=stat.S_IMODE(info.st_mode),
    )


def transform_file(source, output, passphrase, decrypt=False, config=None,
                   deny_legacy_cbc=False, overwrite=False, allowed_roots=ALLOWED_ROOTS,
                   transit_client=None):
    source = Path(source)
    output = Path(output)
    source_info = validate_ovirt_path(source, allowed_roots=allowed_roots)
    validate_ovirt_path(output, must_exist=output.exists(), allowed_roots=allowed_roots)
    if source.resolve() != output.resolve() and output.exists() and not overwrite:
        raise EncryptorError("Output exists; use --overwrite to replace it")
    data = source.read_bytes()
    if decrypt:
        result = decrypt_bytes(data, passphrase, config, deny_legacy_cbc, transit_client,
                               allowed_roots)
        output_mode = 0o600
    else:
        if is_encrypted(data):
            raise EncryptorError("File already uses an encrypted envelope format")
        if transit_client:
            result = encrypt_vault_bytes(data, transit_client)
            # Verify before replacing any persistent file.
            verified = decrypt_vault_bytes(result, transit_client)
        else:
            dek, _created = ensure_dek(config or {}, passphrase, allowed_roots=allowed_roots)
            try:
                result = encrypt_envelope(data, dek)
                verified = decrypt_envelope(result, dek)
            finally:
                wipe(dek)
        if verified != data:
            raise EncryptorError("Post-encryption self-verification failed")
        output_mode = stat.S_IMODE(source_info.st_mode)
    _atomic_write(
        output,
        result,
        owner=(source_info.st_uid, source_info.st_gid),
        mode=output_mode,
    )


def _parser():
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("-e", "--encrypt", action="store_true")
    action.add_argument("-d", "--decrypt", action="store_true")
    parser.add_argument("source")
    parser.add_argument("output", nargs="?")
    parser.add_argument("--config", default=str(DEFAULT_CONFIG))
    parser.add_argument("--secret-file")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--deny-legacy-cbc", action="store_true")
    parser.add_argument("--prompt", action="store_true")
    return parser


def main(argv=None):
    args = _parser().parse_args(argv)
    try:
        config = _load_crypto_config(args.config)
        transit_client = vault_client_from_config(config)
        passphrase = None
        needs_passphrase = transit_client is None
        if args.decrypt and transit_client is not None:
            with Path(args.source).open("rb") as source:
                needs_passphrase = source.read(len(MAGIC)) in (MAGIC, ENVELOPE_MAGIC)
        if needs_passphrase:
            passphrase = obtain_passphrase(
                config, args.secret_file, args.prompt, transit_client
            )
        transform_file(
            args.source,
            args.output or args.source,
            passphrase,
            decrypt=args.decrypt,
            config=config,
            deny_legacy_cbc=args.deny_legacy_cbc,
            overwrite=args.overwrite,
            transit_client=transit_client,
        )
    except (EncryptorError, OSError) as error:
        print("encryptor: %s" % error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
